### ISSUE TITLE
About trained model and data

### ISSUE THREAD

**Issue by kapitsa2811** [Ellqany/AOCR#1]
Thanks for your work,

Can you please also share trained model and dataset..

**Comment by Ellqany** [comment]
Thank you for your comment,

Sorry for the late replay
I can provide you with a sample of trainned data but I can not with the model

[Data.zip](https://github.com/Ellqany/AOCR/files/7358141/Data.zip)

but for the record
I do not save the model while training. I only save its weight

**Comment by kapitsa2811** [comment]
Thank you
